<?php

<<<<<<<< Updated upstream:backend/var/cache/dev/ContainerUhYUuYy/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
namespace ContainerUhYUuYy;
========
namespace Container0NkFows;
>>>>>>>> Stashed changes:backend/var/cache/dev/Container0NkFows/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.value_resolver.argument_resolver.not_tagged_controller' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/NotTaggedControllerValueResolver.php';

<<<<<<<< Updated upstream:backend/var/cache/dev/ContainerUhYUuYy/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
        return $container->privates['.debug.value_resolver.argument_resolver.not_tagged_controller'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\NotTaggedControllerValueResolver(($container->privates['.service_locator.KzIi.aI'] ?? $container->load('get_ServiceLocator_KzIi_AIService'))), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
========
        return $container->privates['.debug.value_resolver.argument_resolver.not_tagged_controller'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\NotTaggedControllerValueResolver(($container->privates['.service_locator.8XH_INA'] ?? $container->load('get_ServiceLocator_8XHINAService'))), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
>>>>>>>> Stashed changes:backend/var/cache/dev/Container0NkFows/get_Debug_ValueResolver_ArgumentResolver_NotTaggedControllerService.php
    }
}
