<?php

<<<<<<<< Updated upstream:backend/var/cache/dev/ContainerWKLXeHK/getCategoryService.php
namespace ContainerWKLXeHK;
========
namespace ContainerV6rZdjZ;

>>>>>>>> Stashed changes:backend/var/cache/dev/ContainerV6rZdjZ/getCategoryService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ohYd3Vy.App\Entity\Category' shared service.
     *
     * @return \App\Entity\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ohYd3Vy": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".');
    }
}
