<?php

<<<<<<<< Updated upstream:backend/var/cache/dev/ContainerWKLXeHK/getCrudService.php
namespace ContainerWKLXeHK;
========
namespace ContainerV6rZdjZ;

>>>>>>>> Stashed changes:backend/var/cache/dev/ContainerV6rZdjZ/getCrudService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Nb584vp.EasyCorp\Bundle\EasyAdminBundle\Config\Crud' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Config\Crud
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Nb584vp": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Config\\Crud" but no such service exists.');
    }
}
