nelmio_cors:
    defaults:
        nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:8090']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', 'OPTIONS']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
        access_control_allow_origin: []
