<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPs02F6o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPs02F6o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPs02F6o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPs02F6o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPs02F6o\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ps02F6o',
    'container.build_id' => '01eac17b',
    'container.build_time' => 1711814255,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPs02F6o');
