<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWIfpLh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWIfpLh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWIfpLh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWIfpLh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKWIfpLh\App_KernelDevDebugContainer([
    'container.build_hash' => 'KWIfpLh',
    'container.build_id' => '68cbf5f0',
    'container.build_time' => 1711558063,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWIfpLh');
