<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerUhYUuYy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhYUuYy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUhYUuYy.legacy');
=======
if (\class_exists(\ContainerV6rZdjZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6rZdjZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6rZdjZ.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerUhYUuYy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUhYUuYy\App_KernelDevDebugContainer([
    'container.build_hash' => 'UhYUuYy',
    'container.build_id' => '1c82e2f9',
    'container.build_time' => 1710839987,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUhYUuYy');
=======
    \class_alias(\ContainerV6rZdjZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV6rZdjZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'V6rZdjZ',
    'container.build_id' => '389fbbaa',
    'container.build_time' => 1711361790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6rZdjZ');
>>>>>>> Stashed changes
